// Database models for Disk Intelligence
// Represents the SQLite schema and provides type-safe database operations

use diesel::prelude::*;
use serde::{Deserialize, Serialize};

// Schema import (generated by diesel)
include!("schema.rs");

// Database model
#[derive(Queryable, Deserialize, Serialize, Debug, Clone)]
pub struct Snapshot {
    pub id: String,
    pub scan_id: String,
    pub root_path: String,
    pub findings_json: String,
    pub extensions_json: String,
    pub scan_info_json: String,
    pub saved_at: String,
    pub total_files: Option<i32>,
    pub total_folders: Option<i32>,
    pub total_size_bytes: Option<i32>,
    pub snapshot_type: String,
    pub target_path: Option<String>,
    pub comparison_json: Option<String>,
    pub comparison_summary_json: Option<String>,
}

// Insertable model
#[derive(Insertable, Deserialize, Serialize, Debug)]
#[diesel(table_name = snapshots)]
pub struct NewSnapshot {
    pub id: String,
    pub scan_id: String,
    pub root_path: String,
    pub findings_json: String,
    pub extensions_json: String,
    pub scan_info_json: String,
    pub saved_at: String,
    pub total_files: Option<i32>,
    pub total_folders: Option<i32>,
    pub total_size_bytes: Option<i32>,
    pub snapshot_type: String,
    pub target_path: Option<String>,
    pub comparison_json: Option<String>,
    pub comparison_summary_json: Option<String>,
}

// Frontend-facing snapshot model (with deserialized JSON)
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct SnapshotData {
    pub id: String,
    pub scan_id: String,
    pub root_path: String,
    pub findings: Vec<Finding>,
    pub extensions: Vec<ExtensionSummary>,
    pub scan_info: ScanInfo,
    pub saved_at: String,
    pub total_files: i32,
    pub total_folders: i32,
    pub total_size_bytes: i32,
    pub snapshot_type: String,
    pub target_path: Option<String>,
    pub comparison: Option<Vec<ComparisonItem>>,
    pub comparison_summary: Option<ComparisonSummary>,
}

// Associated data structures
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Finding {
    pub id: String,
    pub category: String,
    pub reason: String,
    pub paths: Vec<String>,
    pub total_bytes: i64,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ExtensionSummary {
    pub extension: String,
    pub file_count: i32,
    pub total_bytes: i64,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ScanInfo {
    pub scan_id: String,
    pub root_path: String,
    pub started_at: String,
    pub completed_at: String,
    pub total_files: i32,
    pub total_folders: i32,
    pub total_size_bytes: i64,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ComparisonItem {
    pub name: String,
    pub relative_path: String,
    pub item_type: String,
    pub status: String,
    pub source_size: Option<i64>,
    pub target_size: Option<i64>,
    pub source_modified: Option<String>,
    pub target_modified: Option<String>,
    pub source_hash: Option<String>,
    pub target_hash: Option<String>,
    pub children: Option<Vec<ComparisonItem>>,
    pub difference_count: i32,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ComparisonSummary {
    pub identical: i32,
    pub modified: i32,
    pub missing_from_target: i32,
    pub extra_in_target: i32,
    pub total_source_size: i64,
    pub total_target_size: i64,
}

// ============================================================================
// Response Types
// ============================================================================

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ComparisonResult {
    pub comparison_id: String,
    pub source_path: String,
    pub target_path: String,
    pub summary: ComparisonSummary,
    pub tree: Vec<ComparisonItem>,
    pub deep_scan: bool,
    pub completed_at: String,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct HealthStatus {
    pub status: String,
    pub version: String,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct DuHastMuchResponse {
    pub results: Vec<DuHastMuchResult>,
    pub total_size: i64,
    pub total_files: i64,
    pub elapsed_seconds: f64,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct DuHastMuchResult {
    pub name: String,
    pub path: String,
    pub size: i64,
    pub files: i64,
    pub latest_mtime: i64,
    pub avg_file_size: i64,
}